version: '3'

services:
  apps:
      build:
        context: .
        dockerfile: ./dockerfile
      command: sh -c "gunicorn --bind unix:/var/demos/frontend_backend_difference/main.sock -m 007 frontend_backend_difference.wsgi"
      ports:
        - "8002:80"