version: '3'

services:
  apps:
      build:
        context: .
        dockerfile: ./dockerfile
      command: sh -c "supervisord --nodaemon --configuration /etc/supervisord.conf"
      ports:
        - "8002:80"