version: '3'

services:
  apps:
      build:
        context: .
        dockerfile: ./dockerfile
      command: sh -c "nginx && gunicorn --bind 0.0.0.0:4000 -m 007 frontend_backend_difference.wsgi"
      ports:
        - "8002:80"