version: '3'

services:
  apps:
      build:
        context: .
        dockerfile: ./dockerfile
      command: sh -c "supervisord --nodaemon --configuration /etc/supervisord.conf"
      ports:
        - "8002:80"
      volumes:
        - ./apps_dev_logs/:/var/log/nginx/
      deploy:
        resources:
          limits:
            memory: 200M
          reservations:
            memory: 100M
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 3
          window: 120s
  nginx:
    image: nginx:1.15.3-alpine
    container_name: production_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/nginx-dev.conf
      - ./empty.conf:/etc/nginx/conf.d/default.conf
      - ./statics/:/var/live-demos/statics/
      - ./nginx_dev_logs/:/var/log/nginx/