version: '3.8'

services:
  apps:
      build:
        context: .
        dockerfile: ./dockerfile
      command: sh -c "supervisord --nodaemon --configuration /etc/supervisord.conf"
      ports:
        - "8002:80"
      deploy:
        resources:
          limits:
            memory: 200M
          reservations:
            memory: 100M
        restart_policy:
          condition: any