version: '3.8'

services:
  apps:
      build:
        context: .
        dockerfile: ./dockerfile
      command: sh -c "supervisord --nodaemon --configuration /etc/supervisord.conf"
      volumes:
        - /etc/letsencrypt/live/demos.coretabs.net/fullchain.pem:/var/cert/fullchain.pem
        - /etc/letsencrypt/live/demos.coretabs.net/privkey.pem:/var/cert/privkey.pem
      ports:
        - "8002:443"
      deploy:
        resources:
          limits:
            memory: 200M
          reservations:
            memory: 100M
        restart_policy:
          condition: any